name: Vulnerability Checks

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  vuln_check:
    name: Vulnerability Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: '1'
          check-latest: true

      - name: install govulncheck
        run: go install "golang.org/x/vuln/cmd/govulncheck@latest"

      - name: prepare go.mod
        run: go mod download

      - name: Run unit tests
        run: |
          go test ./...

      - name: Run go vet
        run: |
          go vet ./...

      - name: Run govulncheck
        run: |
          govulncheck ./...

      - name: Run fuzz test (short)
        run: |
          go test -fuzz=FuzzDetectFlavorFromArmor -run=^$ -fuzztime=5s ./whichpgp
