# Vulnerability Checks Workflow
#
# This workflow runs security and vulnerability checks on the codebase, including:
# - Unit tests with coverage
# - Race condition detection
# - Static analysis (go vet)
# - Linting (golangci-lint)
# - Vulnerability scanning (govulncheck)
# - Fuzz testing for robustness
#
# Fuzz Testing:
# - Automatic runs: Short 10-second fuzz tests on all APIs (PRs and pushes)
# - Manual dispatch: Extended 1-minute fuzz tests for deeper vulnerability discovery
#   To run extended tests: Go to Actions tab → "Vulnerability Checks" → "Run workflow"
#
# The fuzz testing is managed via Makefile, which automatically discovers and runs
# all available fuzz functions. No workflow updates needed when adding new fuzz tests.
#
name: Vulnerability Checks

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  vuln_check:
    name: Vulnerability Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: '1'
          check-latest: true

      - name: Install dependencies
        # We install the latest version due to the fail-fast policy
        run: |
          go install "golang.org/x/vuln/cmd/govulncheck@latest"
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Download Go modules
        run: make deps

      - name: Run unit tests with coverage
        run: make test-unit

      - name: Run tests with race condition detection
        run: make test-race

      - name: Run go vet
        run: |
          go vet ./...

      - name: Run linter checks
        run: make test-lint

      - name: Run govulncheck
        run: |
          govulncheck ./...

      - name: Run fuzz tests (short - 10s each)
        run: make test-fuzz-short

      - name: Run extended fuzz tests (manual trigger only - 1m each)
        if: github.event_name == 'workflow_dispatch'
        run: make test-fuzz
